name: Upload files to UCSD's server

on:
  push:
    branches:
    - github-action

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    
    - name: checkout
      uses: actions/checkout@v3.0.2

    - name: Copy files via ssh username, host, and password
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOSTNAME }}
        username: ${{ secrets.USER }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        source: "*"
        target: "${{ secrets.HOME_DIR }}/test"