name: Upload files to UCSD's server

on:
  push:
    branches:
    - github-action

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    
    # Checkout
    - uses: actions/checkout@master

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        mkdir ../build
        cp -TR . ../build
        tar -cvf deploy.tar ../build/

    # SCP to UCSD server and copy the website files
    - name: Copy files via ssh username, host, and password
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOSTNAME }}
        username: ${{ secrets.USER }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        source: "deploy.tar"
        target: "${{ secrets.HOME_DIR }}/test"