name: Upload files to UCSD's server

on:
  push:
    branches:
    - github-action

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    
    - name: Install sshpass
      run: sudo apt install -y sshpass

    # Checkout
    - name: Checkout the repo
      uses: actions/checkout@master
      with:
        path: my-repo

    - name: Upload repo to remote server
      run: |
        sshpass -p "${{ secrets.PASSWORD }}" scp -p ${{ secrets.PORT }} -r my-repo ${{ secrets.USER }}@${{ secrets.HOST }}:${{ secrets.HOME_DIR }}/test/