name: Upload files to UCSD's server

on:
  push:
    branches:
    - github-action

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    
    # Checkout
    - name: Checkout the repo
      uses: actions/checkout@master
      with:
        path: my-repo

    - name: Upload repo to remote server
      run: |
        scp -r -P ${{ secrets.PORT }} my-repo ${{ secrets.USER }}@${{ secrets.HOST }}:${{ secrets.HOME_DIR }}/test

    # # SCP to UCSD server and copy the website files
    # - name: Copy folder content recursively to remote
    #   uses: garygrossgarten/github-action-scp@release
    #   with:
    #     host: ${{ secrets.HOST }}
    #     username: ${{ secrets.USER }}
    #     password: ${{ secrets.PASSWORD }}
    #     port: ${{ secrets.PORT }}
    #     local: "./test"
    #     remote: "${{ secrets.HOME_DIR }}/test/"